arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - horizontal_x
    - horizontal_y
    - vertical_z
    - boro_theta
    - blisk_rotate
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    horizontal_x:  {trajectory: 0.1, goal: 0.1}
    horizontal_y: {trajectory: 0.1, goal: 0.1}
    vertical_z: {trajectory: 0.1, goal: 0.1}
    boro_theta: {trajectory: 0.1, goal: 0.1}
    blisk_rotate: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
